language: java
jdk:
  - openjdk15

sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - denisill@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

#env:
#  global:
#    - CODECOV_TOKEN="dca401a0-aa7c-4758-8259-9c2e5dbea0e0"